// ==========================================
// AI Agent Modular Tools System & Registry
// Manages tool registration, OpenAI schema definitions,
// argument validation, secure dispatch, and execution logging
// ==========================================

import type { ChatCompletionTool } from 'openai/resources/chat/completions';
import { AgentTool, ToolExecutionContext, ToolCallLog } from './types';
import { calculatorTool } from './calculator';
import { assignmentsTool } from './assignments';
import { studyPlanTool } from './studyPlan';
import { notesSearchTool } from './notesSearch';

export * from './types';
export * from './calculator';
export * from './assignments';
export * from './studyPlan';
export * from './notesSearch';

// ------------------------------------------
// Tool Registry State
// ------------------------------------------

const registeredTools = new Map<string, AgentTool>();
const executionLogs: ToolCallLog[] = [];

/**
 * Register a new AgentTool in the modular tool system.
 */
export function registerTool(tool: AgentTool): void {
  if (!tool.name || typeof tool.name !== 'string') {
    throw new Error('Tool must have a valid string name.');
  }
  registeredTools.set(tool.name, tool);
}

// Register default built-in academic tools
registerTool(calculatorTool);
registerTool(assignmentsTool);
registerTool(studyPlanTool);
registerTool(notesSearchTool);

/**
 * Retrieve all currently registered Agent Tools.
 */
export function getRegisteredTools(): AgentTool[] {
  return Array.from(registeredTools.values());
}

/**
 * Convert registered tools to OpenAI Chat Completion Tools format.
 */
export function getOpenAIToolsDefinition(): ChatCompletionTool[] {
  return getRegisteredTools().map((tool) => ({
    type: 'function',
    function: {
      name: tool.name,
      description: tool.description,
      parameters: tool.parameters as unknown as Record<string, unknown>,
    },
  }));
}

/**
 * Retrieve recent tool call logs for debugging and audit inspection.
 */
export function getToolExecutionLogs(limit = 20): ToolCallLog[] {
  return executionLogs.slice(-limit);
}

/**
 * Validate arguments against parameter schema required fields.
 */
function validateToolArguments(tool: AgentTool, args: Record<string, any>): void {
  if (tool.parameters.required && Array.isArray(tool.parameters.required)) {
    for (const requiredField of tool.parameters.required) {
      if (args[requiredField] === undefined || args[requiredField] === null) {
        throw new Error(
          `Argument Validation Error: Tool '${tool.name}' is missing required parameter '${requiredField}'.`
        );
      }
    }
  }
}

export interface ToolExecutionResponse {
  toolName: string;
  success: boolean;
  result: any;
  error?: string;
  durationMs: number;
}

/**
 * Safely execute a tool call generated by the LLM.
 *
 * Enforces:
 * - Only registered tools can be executed (rejects arbitrary calls).
 * - Safe JSON argument parsing and schema validation.
 * - Injects verified user authorization context.
 * - Comprehensive logging for observability and debugging.
 */
export async function executeToolCall(
  call: { name: string; arguments: string | Record<string, any> },
  context: ToolExecutionContext
): Promise<ToolExecutionResponse> {
  const startTime = Date.now();
  const toolName = call.name;

  console.log(`[Tool Dispatcher] Initiating execution for tool '${toolName}'...`);

  // 1. Verify that tool is registered
  const tool = registeredTools.get(toolName);
  if (!tool) {
    const errorMsg = `Security Rejection: Tool '${toolName}' is not a registered agent tool.`;
    console.error(`[Tool Dispatcher Error] ${errorMsg}`);
    return {
      toolName,
      success: false,
      result: null,
      error: errorMsg,
      durationMs: Date.now() - startTime,
    };
  }

  // 2. Parse arguments safely
  let parsedArgs: Record<string, any> = {};
  if (typeof call.arguments === 'string') {
    try {
      parsedArgs = JSON.parse(call.arguments || '{}');
    } catch (parseErr) {
      const errorMsg = `Argument Parsing Error: Failed to parse JSON arguments for tool '${toolName}'.`;
      console.error(`[Tool Dispatcher Error] ${errorMsg}`, parseErr);
      return {
        toolName,
        success: false,
        result: null,
        error: errorMsg,
        durationMs: Date.now() - startTime,
      };
    }
  } else if (typeof call.arguments === 'object' && call.arguments !== null) {
    parsedArgs = call.arguments;
  }

  // 3. Validate arguments
  try {
    validateToolArguments(tool, parsedArgs);
  } catch (valErr) {
    const errorMsg = valErr instanceof Error ? valErr.message : 'Argument validation failure';
    console.warn(`[Tool Validation Warning] ${errorMsg}`);
    return {
      toolName,
      success: false,
      result: null,
      error: errorMsg,
      durationMs: Date.now() - startTime,
    };
  }

  // 4. Execute tool
  try {
    console.log(`[Tool Execution] Calling '${toolName}' with args:`, JSON.stringify(parsedArgs));
    const result = await tool.execute(parsedArgs, context);
    const durationMs = Date.now() - startTime;

    console.log(
      `[Tool Execution Success] '${toolName}' finished in ${durationMs}ms. Result summary:`,
      typeof result === 'object' && result !== null ? Object.keys(result) : result
    );

    // Record execution log
    executionLogs.push({
      toolName,
      arguments: parsedArgs,
      result,
      durationMs,
      timestamp: new Date().toISOString(),
    });

    return {
      toolName,
      success: true,
      result,
      durationMs,
    };
  } catch (execErr) {
    const durationMs = Date.now() - startTime;
    const errorMsg = execErr instanceof Error ? execErr.message : 'Unknown tool execution error';

    console.error(`[Tool Execution Error] '${toolName}' failed after ${durationMs}ms:`, execErr);

    executionLogs.push({
      toolName,
      arguments: parsedArgs,
      error: errorMsg,
      durationMs,
      timestamp: new Date().toISOString(),
    });

    return {
      toolName,
      success: false,
      result: null,
      error: errorMsg,
      durationMs,
    };
  }
}
